### ISSUE TITLE
valid sound file paths

### ISSUE THREAD

**Issue by Bibiko** [clld/soundcomparisons-data#10]
@xrotwang 
I created a command `write_valid_soundfilepaths` which writes the file `valid_soundfilepaths.txt`. Please keep in mind that these file paths are the **prefixes only**. In order find valid paths one has to consider that `_lex2`, `_lex3`, ... or `_pron2`, `pron3`, ... plus `.{wav|mp3|ogg}` can follow.

A possible regex could be:

_valid sound file path_(_lex\d+)?(_pron\d+)?\\.(wav|mp3|ogg)

**Comment by xrotwang** [comment]
Ah, nice. I've seen the "alternative lexeme" and "pronunciation variant" columns in the database. Do you think these could be used to fully enumerate all valid paths, i.e. spelling out which `_lex` or `_pron` suffix are actually possible?

**Comment by Bibiko** [comment]
I think so. I'll do it tomorrow since I want to clarify first whether some legacy data are handled differently.

**Comment by xrotwang** [comment]
Haha. "handled differently" sounds scary - but so does >10 years of legacy :)

**Comment by Bibiko** [comment]
now the command `write_valid_soundfilepaths` provides all in the DB given`_lex*` and `_pron*` info
