### ISSUE TITLE
pysoundcomparisons command to create offline version

### ISSUE THREAD

**Issue by xrotwang** [clld/soundcomparisons-data#11]
The [current PHP script](https://github.com/lingdb/Sound-Comparisons/blob/master/script/generateOffline.php) should be replaced by a `pysoundcomparisons` command (in the first step with the same functionality).

**Comment by Bibiko** [comment]
done with the new command `create_offline_version` which is fully functional -- some minor additions will follow as to be able to set up the folder `sound` by passing the desired studies
