### ISSUE TITLE
How uploads are done/catalog.json is populated

### ISSUE THREAD

**Issue by chrzyki** [clld/soundcomparisons-data#7]
This might a be a good project to document, for reference and future projects, how files are uploaded to a CDSTAR instance and how `catalog.json` (or similar) is populated. I have a step-by-step guide in mind, i.e. install this library, run this command, check this file, etc.

**Comment by xrotwang** [comment]
Yes, good idea. Although pydictionaria may even be better, since it
actually uses cdstarcat **and** a local catalog.

Christoph Rzymski <notifications@github.com> schrieb am Di., 26. Juni 2018,
14:20:

**Comment by xrotwang** [comment]
I think this should go into the (not yet existing) documentation for [clld/cdstarcat](https://github.com/clld/cdstarcat); will add a bit to the `README.md`, there, and maybe link to examples of usage in some projects.

**Comment by chrzyki** [comment]
Thanks! See https://github.com/clld/cdstarcat/commit/a4a4a56bf18b6de1cc03ce77475fb986469b8436 and the [clld/cdstarcat](https://github.com/clld/cdstarcat) repository.
